import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { caveat } from "@/app/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={caveat.className}>
				<Header />
				{children}
			</body>
		</html>
	);
}
